name: Demo to setup a project with GitHub Actions

on:
  push:
    branches:
      - main

jobs:
  UpdateAuthor:
    runs-on: ubuntu-latest

    steps:
    - name: Checking out code
      uses: actions/checkout@v2

    - name: Extract commit data
      uses: rlespinasse/git-commit-data-action@v1.x

    - name: Update author information
      run: echo Author Information updated

    - name: Raise PR
      uses: peter-evans/create-pull-request@v3
      with:
        branch: "QA"
        base: main
        title: "Demo for auto PR"
        body: |
          This is to show automatic PR creation.
        token: ${{ secrets.GITHUB_TOKEN }}
        
