name: Auto Create Pull Request

on:
  push:
    branches:
      - main

jobs:
  create_pull_request:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Extract git commit data
      uses: rlespinasse/git-commit-data-action@v1.x

    - name: Update author information
      run: echo ${{ env.GIT_COMMIT_AUTHOR_NAME }} > AUTHOR

    - name: Configure Git
      run: |
        git config --global user.name "${{ env.GIT_COMMIT_AUTHOR_NAME }}"
        git config --global user.email "${{ env.GIT_COMMIT_AUTHOR_EMAIL }}"

    - name: Commit changes
      run: |
        git add AUTHOR
        git commit -m "Update author information"

    - name: Create or Update Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        branch: "QA"
        base: main
        title: "Auto-created Pull Request"
        committer: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}>
        author: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}>
        body: |
          This pull request was automatically created by GitHub Actions.
        token: ${{ secrets.GITHUB_TOKEN }}
        delete-branch: true
