name: Create Pull Request from main to QA

on:
  push:
    branches:
      - main

jobs:
  create_pull_request:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        source: main
        destination: QA
        title: 'Sync main to QA'
        body: |
          This is an automated pull request to sync changes from the main branch to the QA branch.
        draft: false
