name: Create Pull Request from Main to QA

on:
  push:
    branches:
      - main

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: Create pull request from main to QA
        branch: QA
        title: Pull request from main to QA
        body: |
          This is an automated pull request created by GitHub Actions to merge changes from the main branch to the QA branch.
        labels: automated-pr
